global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['10.0.1.222:8080']

  - job_name: 'pgexporter'
    static_configs:
      - targets: ['10.0.1.222:9187']