global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']  # EC2에서 Docker → EC2 host

  - job_name: 'pgexporter'
    static_configs:
      - targets: ['postgres-exporter:9187']