global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api.u-hyu.site']

  - job_name: 'pgexporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
