version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3  # PostGIS 포함된 공식 이미지
    container_name: local-postgis
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
