spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_REST_API_KEY}
            client-name: Kakao
            redirect-uri: "https://api.u-hyu.site/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - name
              - gender
              - age_range
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false # 운영에서는 SQL 로그 비활성화 추천

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration-time: ${ACCESS_TOKEN_EXP}
  refresh-token-expiration-days: ${REFRESH_TOKEN_EXP}
  cookie:
    domain: u-hyu.site
    secure: true
    same-site: Lax

domain:
  base-url: https://www.u-hyu.site

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: info
