spring:
  application:
    name: uhyu
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev} # 기본값 dev, 환경변수로 override 가능

app:
  frontend:
    url:
      local: http://localhost:5173
      prod: https://www.u-hyu.site